name: SP TikTok - Main Upload
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sp-tiktok
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run main-upload
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.SP_IG_GOOGLE_SERVICE_ACCOUNT_KEY }}
          BUFFER_API_KEY: ${{ secrets.BUFFER_API_KEY }}
          GOOGLE_DRIVE_API_KEY: ${{ secrets.SP_IG_GOOGLE_DRIVE_API_KEY }}
